// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6k0yeXZss_y2QcL2JFBE4ALeexfD_Gog',
    appId: '1:386221740205:web:8e60870d314d2a6aa5f624',
    messagingSenderId: '386221740205',
    projectId: 'trigo-ab9be',
    authDomain: 'trigo-ab9be.firebaseapp.com',
    storageBucket: 'trigo-ab9be.firebasestorage.app',
    measurementId: 'G-0RG801Q57Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLJEVqAiMbH95zMlL9hyTw7G-OG-aajVM',
    appId: '1:386221740205:android:bbb71dc59bc2e47da5f624',
    messagingSenderId: '386221740205',
    projectId: 'trigo-ab9be',
    storageBucket: 'trigo-ab9be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyZ4Yur1phyniKiNqCGfN7QTxX-W7gM-Q',
    appId: '1:386221740205:ios:67b16522da45fb97a5f624',
    messagingSenderId: '386221740205',
    projectId: 'trigo-ab9be',
    storageBucket: 'trigo-ab9be.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyZ4Yur1phyniKiNqCGfN7QTxX-W7gM-Q',
    appId: '1:386221740205:ios:67b16522da45fb97a5f624',
    messagingSenderId: '386221740205',
    projectId: 'trigo-ab9be',
    storageBucket: 'trigo-ab9be.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6k0yeXZss_y2QcL2JFBE4ALeexfD_Gog',
    appId: '1:386221740205:web:6f4983c6f77c7559a5f624',
    messagingSenderId: '386221740205',
    projectId: 'trigo-ab9be',
    authDomain: 'trigo-ab9be.firebaseapp.com',
    storageBucket: 'trigo-ab9be.firebasestorage.app',
    measurementId: 'G-N5VH327WHC',
  );
}
